resource/aws_cognito_user_pool: Fix perpetual diffs on sms_verification_message
When using `verification_message_template.sms_message` for setting the sms message verification template the resource upon re-applys would trigger an update because of a diff in the conflicting `sms_verification_message` argument. This changes adds the computed property onto `sms_message_verification` to ensure it get's updated with the contents being set by `verification_message_template.sms_message`

Acceptance test before change
```
--- FAIL: TestAccAWSCognitoUserPool_withVerificationMessageTemplate (10.90s)                                                                                                                                                         [274/322]
    testing.go:568: Step 0 error: After applying this step, the plan was not empty:

        DIFF:

        UPDATE: aws_cognito_user_pool.pool
          sms_verification_message:                                "{####} Baz" => ""

```

Acceptance test after change
```
--- PASS: TestAccAWSCognitoUserPool_withVerificationMessageTemp
```